---
title: "GARCH One-Step Ahead"
author: "Mike Aguilar"
date: "3/30/2022"
output: html_document
---

```{css, echo=FALSE}
.scroll-200 {
  max-height: 200px;
  overflow-y: auto;
  background-color: inherit;
}
```


```{r, include=TRUE, echo = FALSE}
knitr::opts_chunk$set(fig.width=10,echo=TRUE, warning=FALSE, message=FALSE, class.output="scroll-200")
```


```{r}
### Housekeeping
rm(list=ls()) # clear workspace
cat("\014")  # clear console

### Load Date
library(quantmod)
startd <-"2012-01-01"  
endd <-"2015-12-31"
ticker <- "^GSPC"
Prices <- Ad(getSymbols(ticker, from = startd, to = endd, auto.assign = FALSE)) # get the adjusted closed price
Returns <- diff(log(Prices)) # get daily log-return
Returns <- na.omit(Returns)
names(Returns)<-"Actual Return"

# Remove mean from data
# Note: means of daily stock returns are VERY small, this step does not matter much
Returns <- Returns - mean(Returns)

# Squared returns/volatility target
SqReturns <- Returns^2

# Split training and test data
Train <- Returns["/2015-11-29"] 
Test <- Returns["2015-11-30/"]
```

```{r}
### Specify Model: GARCH(1,1)
library(rugarch)
spec <- ugarchspec(variance.model=list(model="sGARCH", garchOrder=c(1,1)),
                   mean.model=list(include.mean = F, armaOrder=c(0,0)), 
                   distribution.model="norm")

# Estimate coefficients
fit <- ugarchfit(spec = spec, data = Returns, out.sample = length(Test)) # note that out-of-sample data is excluded by indicating out.sample = length(Test)
coef(fit)
```


```{r}
### Make Static One-Step Ahead Forecast with GARCH Model
Forecast <- ugarchforecast(fitORspec = fit, n.ahead = 1, n.roll=length(Test)-1) 

# Forecast for volatility(sigma)
Forecast_Volatility <- data.frame(t(sigma(Forecast)))
names(Forecast_Volatility) <- rownames(sigma(Forecast))
Forecast_Volatility # Note that the date shown is when the forecast was made
```


```{r}
### Plot Forecasts
# Variance
PlotVariance = cbind(xts(Forecast_Volatility^2, order.by=index(Test)),
                       sigma(fit)^2, SqReturns)
PlotVariance = 252*PlotVariance
colnames(PlotVariance) <- c("Forecast", "ModelFitted", "Proxy(ret^2)")
# Plot
{plot(PlotVariance, col = c("red","blue","black"), lwd = 2, ylab = "Annual Variance",
     main = "Dynamic One-Step Ahead Forecast \n with GARCH(1,1) Model", legend.loc = "topleft")
addEventLines(xts("training", index(Test)[1]), srt=90, pos=2, lty = 2, lwd = 2, col = "blue") }


### MSE for GARCH 
MSE <- rbind("GARCH(1,1)" = c(mean((SqReturns - PlotVariance$ModelFitted)^2,na.rm = T),
                              mean((SqReturns - PlotVariance$Forecast)^2, na.rm = T)))
colnames(MSE) <- c("In-sample MSE", "Out-of-sample MSE")
print(MSE)
```