---
title: "Static ARIMA Multi-Step Ahead"
author: "Mike Aguilar"
date: "3/30/2022"
output: html_document
---

```{css, echo=FALSE}
.scroll-200 {
  max-height: 200px;
  overflow-y: auto;
  background-color: inherit;
}
```


```{r, include=TRUE, echo = FALSE}
knitr::opts_chunk$set(fig.width=10,echo=TRUE, warning=FALSE, message=FALSE, class.output="scroll-200")
```

 
```{r}
### Houesekeeping
rm(list=ls()) # clear workspace
cat("\014")  # clear console

### Load Data
#library(Quandl)
#Quandl_key = read.csv("quandlkey.csv",stringsAsFactors=FALSE)$Key
#Quandl.api_key(Quandl_key)
#startd<-"1990-01-01"
#endd<-"2018-12-31"
#freq<-"quarterly"
#GDP <- Quandl("FRED/GDPC1", type="ts",start_date=startd, end_date=endd)
#GDPGrowth <- diff(log(GDP)) # calculate log growth rate
#GDPGrowth <- na.omit(GDPGrowth) # get rid of the NAs

library(quantmod)
startd<-"1990-01-01"
endd<-"2020-12-31"
Ticker = "GDPC1"
getSymbols(Ticker,from=startd,to=endd,src='FRED')
Growth<-diff(log(GDPC1))
Growth<-na.omit(Growth)
colnames(Growth)=c("Growth")
# Split Data
Train <-Growth["/2014"]
Test<-Growth["2015/"]

```



```{r}
### Dynamic Multi-Step Ahead Forecast with ARIMA Model
library(forecast)
fit<-auto.arima(Train)

# Make 5-step ahead forecast
StepNum = 5
ARIMAForecast <- forecast(fit, h = StepNum) # h is the forecast step number
ARIMAForecast  
```
