---
title: "Max Sharpe - Fully Invested & Long/Short (Rebalancing)"
author: "Mike Aguilar"
date: "3/30/2022"
output: html_document
---



```{r, include=TRUE, echo = FALSE}
knitr::opts_chunk$set(fig.width=10,echo=TRUE, warning=FALSE, message=FALSE, class.output="scroll-200")
```


```{r}
### Housekeeping
rm(list=ls()) # clear workspace
cat("\014")  # clear console

### Housekeeping
rm(list=ls()) # clear workspace
cat("\014")  # clear console
### Load Data
library(quantmod)
startd = "2015-01-01"
endd = "2021-04-30"
Tickers = c("IBM","GE","F","MSFT")
getSymbols(Tickers,from=startd,to=endd,src='yahoo')
### Compute Returns
Return = do.call(merge,lapply(Tickers, function(x) 
        periodReturn(Ad(get(x)),period='daily',type='arithmetic')))
Return = na.omit(Return[-1,])
colnames(Return)<-Tickers

### Construct Portfolio
# Create the portfolio specification
library(PortfolioAnalytics)
init.portf <-portfolio.spec(assets = colnames(Return))

# Add a full investment constraint such that the weights sum to 1
init.portf <- add.constraint(portfolio=init.portf, type="full_investment")


# Add risk and return objective(we need them to calculate the Sharpe ratio)
init.portf <- add.objective(portfolio=init.portf, type="return", name = "mean")
init.portf <- add.objective(portfolio=init.portf, type="risk", name = "StdDev")
```


```{r}
### Solve Portfolio: Maximize Sharpe Ratio
# The default action if “mean” and “StdDev” are specified as objectives with optimize_method="ROI" is to maximize quadratic utility. If we want to maximize Sharpe Ratio, we need to pass in maxSR=TRUE to optimize.portfolio
library(ROI)
opt.MaxSR <- optimize.portfolio(R=Return, 
                                portfolio=init.portf, 
                                optimize_method="ROI", 
                                maxSR=TRUE,
                                trace=TRUE)
# Warning: Inf or -Inf values detected in box constraints, maximum return objectives must have finite box constraint values. 



summary(opt.MaxSR) # The optimization summary should be read carefully since not every constraint is guaranteed to be satisfied
```

Caution: The function is called "rebalancing" but the implementation reoptimizes the weights. 
```{r}
### Solve Portfolio: Maximize Sharpe Ratio with Re-balancing
# Quarters rebalancing with 4 year training period and 1 year rolling window
opt.MaxSR.Rebal <- optimize.portfolio.rebalancing(
                                            R = Return, 
                                            portfolio = init.portf,
                                            optimize_method = 'ROI',
                                            maxSR=TRUE,
                                            trace = TRUE,
                                            rebalance_on = 'quarters',
                                            training_period = 4*252,
                                            rolling_window = 252)
# Warning: Inf or -Inf values detected in box constraints, maximum return objectives must have finite box constraint values. 


summary(opt.MaxSR.Rebal) 
```




```{r}
### Visualize result
library(PerformanceAnalytics)
# Optimal weights
OptWeight = extractWeights(opt.MaxSR)
OptWeight.Rebal = extractWeights(opt.MaxSR.Rebal)

chart.Weights(opt.MaxSR)
chart.Weights(opt.MaxSR.Rebal)


# Portfolio return
PortReturn <- Return.portfolio(R = Return, 
                              weights = OptWeight, 
                              geometric = FALSE) #use arithmetic(FALSE) to aggregate returns
PortReturn.Rebal <- Return.portfolio(R = Return, 
                              weights = OptWeight.Rebal, 
                              geometric = FALSE) 

Portfolio.R = cbind(PortReturn,PortReturn.Rebal)
names(Portfolio.R) = c("Non-Rebalancing","Rebalancing")

# First rebalance date: 2019-03-29
charts.PerformanceSummary(Portfolio.R, colors=c("darkred","steelblue"), main=" ") 

```



